/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

/**
 * Rate limited
 */
export type RateLimitedResponseData = {
  error?: components.ErrorObject | null | undefined;
  limits?: components.LimitsObject | null | undefined;
};

/**
 * Rate limited
 */
export class RateLimitedResponse extends Error {
  error?: components.ErrorObject | null | undefined;
  limits?: components.LimitsObject | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: RateLimitedResponseData;

  constructor(err: RateLimitedResponseData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.error != null) this.error = err.error;
    if (err.limits != null) this.limits = err.limits;

    this.name = "RateLimitedResponse";
  }
}

/** @internal */
export const RateLimitedResponse$inboundSchema: z.ZodType<
  RateLimitedResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.nullable(components.ErrorObject$inboundSchema).optional(),
  limits: z.nullable(components.LimitsObject$inboundSchema).optional(),
})
  .transform((v) => {
    return new RateLimitedResponse(v);
  });

/** @internal */
export type RateLimitedResponse$Outbound = {
  error?: components.ErrorObject$Outbound | null | undefined;
  limits?: components.LimitsObject$Outbound | null | undefined;
};

/** @internal */
export const RateLimitedResponse$outboundSchema: z.ZodType<
  RateLimitedResponse$Outbound,
  z.ZodTypeDef,
  RateLimitedResponse
> = z.instanceof(RateLimitedResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.nullable(components.ErrorObject$outboundSchema).optional(),
    limits: z.nullable(components.LimitsObject$outboundSchema).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RateLimitedResponse$ {
  /** @deprecated use `RateLimitedResponse$inboundSchema` instead. */
  export const inboundSchema = RateLimitedResponse$inboundSchema;
  /** @deprecated use `RateLimitedResponse$outboundSchema` instead. */
  export const outboundSchema = RateLimitedResponse$outboundSchema;
  /** @deprecated use `RateLimitedResponse$Outbound` instead. */
  export type Outbound = RateLimitedResponse$Outbound;
}
