/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { analyzeGoogleLogoDetection } from "../../funcs/analyzeGoogleLogoDetection.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.BaseAnalyzeRequest$inboundSchema,
};

export const tool$analyzeGoogleLogoDetection: ToolDefinition<typeof args> = {
  name: "analyze-google-logo-detection",
  description: `Analyze - Google Logo Detection

Detects popular product logos within an image.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await analyzeGoogleLogoDetection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
