/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { analyzeAiVisionGeneral } from "../../funcs/analyzeAiVisionGeneral.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.AnalyzeAIVisionGeneralRequest$inboundSchema,
};

export const tool$analyzeAiVisionGeneral: ToolDefinition<typeof args> = {
  name: "analyze-ai-vision-general",
  description: `Analyze - AI Vision General

The General mode serves a wide array of applications by providing detailed answers to diverse questions about an image. Users can inquire about any aspect of an image, such as identifying objects, understanding scenes, or interpreting text within the image.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await analyzeAiVisionGeneral(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
