/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { analyzeCaptioning } from "../../funcs/analyzeCaptioning.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.BaseAnalyzeRequest$inboundSchema,
};

export const tool$analyzeCaptioning: ToolDefinition<typeof args> = {
  name: "analyze-captioning",
  description: `Analyze - Captioning

Provides a caption for an image.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await analyzeCaptioning(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
