/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { analyzeGoogleTagging } from "../../funcs/analyzeGoogleTagging.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.BaseAnalyzeRequest$inboundSchema,
};

export const tool$analyzeGoogleTagging: ToolDefinition<typeof args> = {
  name: "analyze-google-tagging",
  description: `Analyze - Google Tagging

Provides tags for an image using Google's tagging service.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await analyzeGoogleTagging(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
