/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { analyzeAiVisionTagging } from "../../funcs/analyzeAiVisionTagging.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.AnalyzeAIVisionTaggingRequest$inboundSchema,
};

export const tool$analyzeAiVisionTagging: ToolDefinition<typeof args> = {
  name: "analyze-ai-vision-tagging",
  description: `Analyze - AI Vision Tagging

The Tagging mode accepts a list of tag names along with their corresponding descriptions. If the image matches the description, which may encompass various elements, it will be appropriately tagged. This approach enables customers to align with their own brand taxonomy, offering a dynamic, flexible, and open method for image classification.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await analyzeAiVisionTagging(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
