/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { analyzeAiVisionModeration } from "../../funcs/analyzeAiVisionModeration.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.AnalyzeAIVisionModerationRequest$inboundSchema,
};

export const tool$analyzeAiVisionModeration: ToolDefinition<typeof args> = {
  name: "analyze-ai-vision-moderation",
  description: `Analyze - AI Vision Moderation

The Moderation mode accepts multiple questions about an image, to which the response provides concise answers of "yes," "no," or "unknown." This functionality allows for a nuanced evaluation of whether the image adheres to specific content policies, creative specs, or aesthetic criteria.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await analyzeAiVisionModeration(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
