/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { tasksGetStatus } from "../../funcs/tasksGetStatus.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  taskId: z.string(),
};

export const tool$tasksGetStatus: ToolDefinition<typeof args> = {
  name: "tasks-get-status",
  description: `Get analysis task status

Get the status of an analysis task.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tasksGetStatus(
      client,
      args.taskId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
