/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Analyze } from "./analyze.js";
import { Tasks } from "./tasks.js";

export class CloudinaryAnalysis extends ClientSDK {
  private _analyze?: Analyze;
  get analyze(): Analyze {
    return (this._analyze ??= new Analyze(this._options));
  }

  private _tasks?: Tasks;
  get tasks(): Tasks {
    return (this._tasks ??= new Tasks(this._options));
  }
}
