/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksGetStatus } from "../funcs/tasksGetStatus.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tasks extends ClientSDK {
  /**
   * Get analysis task status
   *
   * @remarks
   * Get the status of an analysis task.
   */
  async getStatus(
    taskId: string,
    options?: RequestOptions,
  ): Promise<components.GetTaskStatusResponse> {
    return unwrapAsync(tasksGetStatus(
      this,
      taskId,
      options,
    ));
  }
}
