/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AnalyzeLvisResponse =
  | components.AnalyzeLvisResponse
  | components.AsyncOperationAcceptedResponse;

/** @internal */
export const AnalyzeLvisResponse$inboundSchema: z.ZodType<
  AnalyzeLvisResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.AnalyzeLvisResponse$inboundSchema,
  components.AsyncOperationAcceptedResponse$inboundSchema,
]);

/** @internal */
export type AnalyzeLvisResponse$Outbound =
  | components.AnalyzeLvisResponse$Outbound
  | components.AsyncOperationAcceptedResponse$Outbound;

/** @internal */
export const AnalyzeLvisResponse$outboundSchema: z.ZodType<
  AnalyzeLvisResponse$Outbound,
  z.ZodTypeDef,
  AnalyzeLvisResponse
> = z.union([
  components.AnalyzeLvisResponse$outboundSchema,
  components.AsyncOperationAcceptedResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnalyzeLvisResponse$ {
  /** @deprecated use `AnalyzeLvisResponse$inboundSchema` instead. */
  export const inboundSchema = AnalyzeLvisResponse$inboundSchema;
  /** @deprecated use `AnalyzeLvisResponse$outboundSchema` instead. */
  export const outboundSchema = AnalyzeLvisResponse$outboundSchema;
  /** @deprecated use `AnalyzeLvisResponse$Outbound` instead. */
  export type Outbound = AnalyzeLvisResponse$Outbound;
}

export function analyzeLvisResponseToJSON(
  analyzeLvisResponse: AnalyzeLvisResponse,
): string {
  return JSON.stringify(
    AnalyzeLvisResponse$outboundSchema.parse(analyzeLvisResponse),
  );
}

export function analyzeLvisResponseFromJSON(
  jsonString: string,
): SafeParseResult<AnalyzeLvisResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyzeLvisResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyzeLvisResponse' from JSON`,
  );
}
