/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AnalyzeAiVisionTaggingResponse =
  | components.AnalyzeAIVisionTaggingResponse
  | components.AsyncOperationAcceptedResponse;

/** @internal */
export const AnalyzeAiVisionTaggingResponse$inboundSchema: z.ZodType<
  AnalyzeAiVisionTaggingResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.AnalyzeAIVisionTaggingResponse$inboundSchema,
  components.AsyncOperationAcceptedResponse$inboundSchema,
]);

/** @internal */
export type AnalyzeAiVisionTaggingResponse$Outbound =
  | components.AnalyzeAIVisionTaggingResponse$Outbound
  | components.AsyncOperationAcceptedResponse$Outbound;

/** @internal */
export const AnalyzeAiVisionTaggingResponse$outboundSchema: z.ZodType<
  AnalyzeAiVisionTaggingResponse$Outbound,
  z.ZodTypeDef,
  AnalyzeAiVisionTaggingResponse
> = z.union([
  components.AnalyzeAIVisionTaggingResponse$outboundSchema,
  components.AsyncOperationAcceptedResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnalyzeAiVisionTaggingResponse$ {
  /** @deprecated use `AnalyzeAiVisionTaggingResponse$inboundSchema` instead. */
  export const inboundSchema = AnalyzeAiVisionTaggingResponse$inboundSchema;
  /** @deprecated use `AnalyzeAiVisionTaggingResponse$outboundSchema` instead. */
  export const outboundSchema = AnalyzeAiVisionTaggingResponse$outboundSchema;
  /** @deprecated use `AnalyzeAiVisionTaggingResponse$Outbound` instead. */
  export type Outbound = AnalyzeAiVisionTaggingResponse$Outbound;
}

export function analyzeAiVisionTaggingResponseToJSON(
  analyzeAiVisionTaggingResponse: AnalyzeAiVisionTaggingResponse,
): string {
  return JSON.stringify(
    AnalyzeAiVisionTaggingResponse$outboundSchema.parse(
      analyzeAiVisionTaggingResponse,
    ),
  );
}

export function analyzeAiVisionTaggingResponseFromJSON(
  jsonString: string,
): SafeParseResult<AnalyzeAiVisionTaggingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyzeAiVisionTaggingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyzeAiVisionTaggingResponse' from JSON`,
  );
}
