/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AnalyzeWatermarkDetectionResponse =
  | components.AnalyzeWatermarkDetectionResponse
  | components.AsyncOperationAcceptedResponse;

/** @internal */
export const AnalyzeWatermarkDetectionResponse$inboundSchema: z.ZodType<
  AnalyzeWatermarkDetectionResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.AnalyzeWatermarkDetectionResponse$inboundSchema,
  components.AsyncOperationAcceptedResponse$inboundSchema,
]);

/** @internal */
export type AnalyzeWatermarkDetectionResponse$Outbound =
  | components.AnalyzeWatermarkDetectionResponse$Outbound
  | components.AsyncOperationAcceptedResponse$Outbound;

/** @internal */
export const AnalyzeWatermarkDetectionResponse$outboundSchema: z.ZodType<
  AnalyzeWatermarkDetectionResponse$Outbound,
  z.ZodTypeDef,
  AnalyzeWatermarkDetectionResponse
> = z.union([
  components.AnalyzeWatermarkDetectionResponse$outboundSchema,
  components.AsyncOperationAcceptedResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnalyzeWatermarkDetectionResponse$ {
  /** @deprecated use `AnalyzeWatermarkDetectionResponse$inboundSchema` instead. */
  export const inboundSchema = AnalyzeWatermarkDetectionResponse$inboundSchema;
  /** @deprecated use `AnalyzeWatermarkDetectionResponse$outboundSchema` instead. */
  export const outboundSchema =
    AnalyzeWatermarkDetectionResponse$outboundSchema;
  /** @deprecated use `AnalyzeWatermarkDetectionResponse$Outbound` instead. */
  export type Outbound = AnalyzeWatermarkDetectionResponse$Outbound;
}

export function analyzeWatermarkDetectionResponseToJSON(
  analyzeWatermarkDetectionResponse: AnalyzeWatermarkDetectionResponse,
): string {
  return JSON.stringify(
    AnalyzeWatermarkDetectionResponse$outboundSchema.parse(
      analyzeWatermarkDetectionResponse,
    ),
  );
}

export function analyzeWatermarkDetectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<AnalyzeWatermarkDetectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyzeWatermarkDetectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyzeWatermarkDetectionResponse' from JSON`,
  );
}
