/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AnalyzeCldTextResponse =
  | components.AsyncOperationAcceptedResponse
  | components.AnalyzeCldTextResponse;

/** @internal */
export const AnalyzeCldTextResponse$inboundSchema: z.ZodType<
  AnalyzeCldTextResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.AsyncOperationAcceptedResponse$inboundSchema,
  components.AnalyzeCldTextResponse$inboundSchema,
]);

/** @internal */
export type AnalyzeCldTextResponse$Outbound =
  | components.AsyncOperationAcceptedResponse$Outbound
  | components.AnalyzeCldTextResponse$Outbound;

/** @internal */
export const AnalyzeCldTextResponse$outboundSchema: z.ZodType<
  AnalyzeCldTextResponse$Outbound,
  z.ZodTypeDef,
  AnalyzeCldTextResponse
> = z.union([
  components.AsyncOperationAcceptedResponse$outboundSchema,
  components.AnalyzeCldTextResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnalyzeCldTextResponse$ {
  /** @deprecated use `AnalyzeCldTextResponse$inboundSchema` instead. */
  export const inboundSchema = AnalyzeCldTextResponse$inboundSchema;
  /** @deprecated use `AnalyzeCldTextResponse$outboundSchema` instead. */
  export const outboundSchema = AnalyzeCldTextResponse$outboundSchema;
  /** @deprecated use `AnalyzeCldTextResponse$Outbound` instead. */
  export type Outbound = AnalyzeCldTextResponse$Outbound;
}

export function analyzeCldTextResponseToJSON(
  analyzeCldTextResponse: AnalyzeCldTextResponse,
): string {
  return JSON.stringify(
    AnalyzeCldTextResponse$outboundSchema.parse(analyzeCldTextResponse),
  );
}

export function analyzeCldTextResponseFromJSON(
  jsonString: string,
): SafeParseResult<AnalyzeCldTextResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyzeCldTextResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyzeCldTextResponse' from JSON`,
  );
}
