/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AnalyzeGoogleTaggingResponse =
  | components.AsyncOperationAcceptedResponse
  | components.AnalyzeGoogleTaggingResponse;

/** @internal */
export const AnalyzeGoogleTaggingResponse$inboundSchema: z.ZodType<
  AnalyzeGoogleTaggingResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.AsyncOperationAcceptedResponse$inboundSchema,
  components.AnalyzeGoogleTaggingResponse$inboundSchema,
]);

/** @internal */
export type AnalyzeGoogleTaggingResponse$Outbound =
  | components.AsyncOperationAcceptedResponse$Outbound
  | components.AnalyzeGoogleTaggingResponse$Outbound;

/** @internal */
export const AnalyzeGoogleTaggingResponse$outboundSchema: z.ZodType<
  AnalyzeGoogleTaggingResponse$Outbound,
  z.ZodTypeDef,
  AnalyzeGoogleTaggingResponse
> = z.union([
  components.AsyncOperationAcceptedResponse$outboundSchema,
  components.AnalyzeGoogleTaggingResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnalyzeGoogleTaggingResponse$ {
  /** @deprecated use `AnalyzeGoogleTaggingResponse$inboundSchema` instead. */
  export const inboundSchema = AnalyzeGoogleTaggingResponse$inboundSchema;
  /** @deprecated use `AnalyzeGoogleTaggingResponse$outboundSchema` instead. */
  export const outboundSchema = AnalyzeGoogleTaggingResponse$outboundSchema;
  /** @deprecated use `AnalyzeGoogleTaggingResponse$Outbound` instead. */
  export type Outbound = AnalyzeGoogleTaggingResponse$Outbound;
}

export function analyzeGoogleTaggingResponseToJSON(
  analyzeGoogleTaggingResponse: AnalyzeGoogleTaggingResponse,
): string {
  return JSON.stringify(
    AnalyzeGoogleTaggingResponse$outboundSchema.parse(
      analyzeGoogleTaggingResponse,
    ),
  );
}

export function analyzeGoogleTaggingResponseFromJSON(
  jsonString: string,
): SafeParseResult<AnalyzeGoogleTaggingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyzeGoogleTaggingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyzeGoogleTaggingResponse' from JSON`,
  );
}
