/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Tag = {
  name?: string | undefined;
};

export type AIVisionTaggingAnalysisData = {
  tags: Array<Tag>;
  modelVersion?: number | undefined;
};

/** @internal */
export const Tag$inboundSchema: z.ZodType<Tag, z.ZodTypeDef, unknown> = z
  .object({
    name: z.string().optional(),
  });

/** @internal */
export type Tag$Outbound = {
  name?: string | undefined;
};

/** @internal */
export const Tag$outboundSchema: z.ZodType<Tag$Outbound, z.ZodTypeDef, Tag> = z
  .object({
    name: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Tag$ {
  /** @deprecated use `Tag$inboundSchema` instead. */
  export const inboundSchema = Tag$inboundSchema;
  /** @deprecated use `Tag$outboundSchema` instead. */
  export const outboundSchema = Tag$outboundSchema;
  /** @deprecated use `Tag$Outbound` instead. */
  export type Outbound = Tag$Outbound;
}

export function tagToJSON(tag: Tag): string {
  return JSON.stringify(Tag$outboundSchema.parse(tag));
}

export function tagFromJSON(
  jsonString: string,
): SafeParseResult<Tag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tag' from JSON`,
  );
}

/** @internal */
export const AIVisionTaggingAnalysisData$inboundSchema: z.ZodType<
  AIVisionTaggingAnalysisData,
  z.ZodTypeDef,
  unknown
> = z.object({
  tags: z.array(z.lazy(() => Tag$inboundSchema)),
  model_version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "model_version": "modelVersion",
  });
});

/** @internal */
export type AIVisionTaggingAnalysisData$Outbound = {
  tags: Array<Tag$Outbound>;
  model_version?: number | undefined;
};

/** @internal */
export const AIVisionTaggingAnalysisData$outboundSchema: z.ZodType<
  AIVisionTaggingAnalysisData$Outbound,
  z.ZodTypeDef,
  AIVisionTaggingAnalysisData
> = z.object({
  tags: z.array(z.lazy(() => Tag$outboundSchema)),
  modelVersion: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    modelVersion: "model_version",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AIVisionTaggingAnalysisData$ {
  /** @deprecated use `AIVisionTaggingAnalysisData$inboundSchema` instead. */
  export const inboundSchema = AIVisionTaggingAnalysisData$inboundSchema;
  /** @deprecated use `AIVisionTaggingAnalysisData$outboundSchema` instead. */
  export const outboundSchema = AIVisionTaggingAnalysisData$outboundSchema;
  /** @deprecated use `AIVisionTaggingAnalysisData$Outbound` instead. */
  export type Outbound = AIVisionTaggingAnalysisData$Outbound;
}

export function aiVisionTaggingAnalysisDataToJSON(
  aiVisionTaggingAnalysisData: AIVisionTaggingAnalysisData,
): string {
  return JSON.stringify(
    AIVisionTaggingAnalysisData$outboundSchema.parse(
      aiVisionTaggingAnalysisData,
    ),
  );
}

export function aiVisionTaggingAnalysisDataFromJSON(
  jsonString: string,
): SafeParseResult<AIVisionTaggingAnalysisData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AIVisionTaggingAnalysisData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AIVisionTaggingAnalysisData' from JSON`,
  );
}
