/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Responses = {
  value?: string | undefined;
};

export type AIVisionGeneralAnalysisData = {
  responses: Array<Responses>;
  modelVersion?: number | undefined;
};

/** @internal */
export const Responses$inboundSchema: z.ZodType<
  Responses,
  z.ZodTypeDef,
  unknown
> = z.object({
  value: z.string().optional(),
});

/** @internal */
export type Responses$Outbound = {
  value?: string | undefined;
};

/** @internal */
export const Responses$outboundSchema: z.ZodType<
  Responses$Outbound,
  z.ZodTypeDef,
  Responses
> = z.object({
  value: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Responses$ {
  /** @deprecated use `Responses$inboundSchema` instead. */
  export const inboundSchema = Responses$inboundSchema;
  /** @deprecated use `Responses$outboundSchema` instead. */
  export const outboundSchema = Responses$outboundSchema;
  /** @deprecated use `Responses$Outbound` instead. */
  export type Outbound = Responses$Outbound;
}

export function responsesToJSON(responses: Responses): string {
  return JSON.stringify(Responses$outboundSchema.parse(responses));
}

export function responsesFromJSON(
  jsonString: string,
): SafeParseResult<Responses, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Responses$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Responses' from JSON`,
  );
}

/** @internal */
export const AIVisionGeneralAnalysisData$inboundSchema: z.ZodType<
  AIVisionGeneralAnalysisData,
  z.ZodTypeDef,
  unknown
> = z.object({
  responses: z.array(z.lazy(() => Responses$inboundSchema)),
  model_version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "model_version": "modelVersion",
  });
});

/** @internal */
export type AIVisionGeneralAnalysisData$Outbound = {
  responses: Array<Responses$Outbound>;
  model_version?: number | undefined;
};

/** @internal */
export const AIVisionGeneralAnalysisData$outboundSchema: z.ZodType<
  AIVisionGeneralAnalysisData$Outbound,
  z.ZodTypeDef,
  AIVisionGeneralAnalysisData
> = z.object({
  responses: z.array(z.lazy(() => Responses$outboundSchema)),
  modelVersion: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    modelVersion: "model_version",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AIVisionGeneralAnalysisData$ {
  /** @deprecated use `AIVisionGeneralAnalysisData$inboundSchema` instead. */
  export const inboundSchema = AIVisionGeneralAnalysisData$inboundSchema;
  /** @deprecated use `AIVisionGeneralAnalysisData$outboundSchema` instead. */
  export const outboundSchema = AIVisionGeneralAnalysisData$outboundSchema;
  /** @deprecated use `AIVisionGeneralAnalysisData$Outbound` instead. */
  export type Outbound = AIVisionGeneralAnalysisData$Outbound;
}

export function aiVisionGeneralAnalysisDataToJSON(
  aiVisionGeneralAnalysisData: AIVisionGeneralAnalysisData,
): string {
  return JSON.stringify(
    AIVisionGeneralAnalysisData$outboundSchema.parse(
      aiVisionGeneralAnalysisData,
    ),
  );
}

export function aiVisionGeneralAnalysisDataFromJSON(
  jsonString: string,
): SafeParseResult<AIVisionGeneralAnalysisData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AIVisionGeneralAnalysisData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AIVisionGeneralAnalysisData' from JSON`,
  );
}
