/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AIVisionGeneralAnalysisData,
  AIVisionGeneralAnalysisData$inboundSchema,
  AIVisionGeneralAnalysisData$Outbound,
  AIVisionGeneralAnalysisData$outboundSchema,
} from "./aivisiongeneralanalysisdata.js";
import {
  LimitsObject,
  LimitsObject$inboundSchema,
  LimitsObject$Outbound,
  LimitsObject$outboundSchema,
} from "./limitsobject.js";

export type Data = {
  entity?: string | undefined;
  analysis?: AIVisionGeneralAnalysisData | undefined;
};

export type AnalyzeAIVisionGeneralResponse = {
  limits?: LimitsObject | null | undefined;
  requestId?: string | undefined;
  data?: Data | undefined;
};

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z
  .object({
    entity: z.string().optional(),
    analysis: AIVisionGeneralAnalysisData$inboundSchema.optional(),
  });

/** @internal */
export type Data$Outbound = {
  entity?: string | undefined;
  analysis?: AIVisionGeneralAnalysisData$Outbound | undefined;
};

/** @internal */
export const Data$outboundSchema: z.ZodType<Data$Outbound, z.ZodTypeDef, Data> =
  z.object({
    entity: z.string().optional(),
    analysis: AIVisionGeneralAnalysisData$outboundSchema.optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Data$ {
  /** @deprecated use `Data$inboundSchema` instead. */
  export const inboundSchema = Data$inboundSchema;
  /** @deprecated use `Data$outboundSchema` instead. */
  export const outboundSchema = Data$outboundSchema;
  /** @deprecated use `Data$Outbound` instead. */
  export type Outbound = Data$Outbound;
}

export function dataToJSON(data: Data): string {
  return JSON.stringify(Data$outboundSchema.parse(data));
}

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const AnalyzeAIVisionGeneralResponse$inboundSchema: z.ZodType<
  AnalyzeAIVisionGeneralResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  limits: z.nullable(LimitsObject$inboundSchema).optional(),
  request_id: z.string().optional(),
  data: z.lazy(() => Data$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
  });
});

/** @internal */
export type AnalyzeAIVisionGeneralResponse$Outbound = {
  limits?: LimitsObject$Outbound | null | undefined;
  request_id?: string | undefined;
  data?: Data$Outbound | undefined;
};

/** @internal */
export const AnalyzeAIVisionGeneralResponse$outboundSchema: z.ZodType<
  AnalyzeAIVisionGeneralResponse$Outbound,
  z.ZodTypeDef,
  AnalyzeAIVisionGeneralResponse
> = z.object({
  limits: z.nullable(LimitsObject$outboundSchema).optional(),
  requestId: z.string().optional(),
  data: z.lazy(() => Data$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnalyzeAIVisionGeneralResponse$ {
  /** @deprecated use `AnalyzeAIVisionGeneralResponse$inboundSchema` instead. */
  export const inboundSchema = AnalyzeAIVisionGeneralResponse$inboundSchema;
  /** @deprecated use `AnalyzeAIVisionGeneralResponse$outboundSchema` instead. */
  export const outboundSchema = AnalyzeAIVisionGeneralResponse$outboundSchema;
  /** @deprecated use `AnalyzeAIVisionGeneralResponse$Outbound` instead. */
  export type Outbound = AnalyzeAIVisionGeneralResponse$Outbound;
}

export function analyzeAIVisionGeneralResponseToJSON(
  analyzeAIVisionGeneralResponse: AnalyzeAIVisionGeneralResponse,
): string {
  return JSON.stringify(
    AnalyzeAIVisionGeneralResponse$outboundSchema.parse(
      analyzeAIVisionGeneralResponse,
    ),
  );
}

export function analyzeAIVisionGeneralResponseFromJSON(
  jsonString: string,
): SafeParseResult<AnalyzeAIVisionGeneralResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyzeAIVisionGeneralResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyzeAIVisionGeneralResponse' from JSON`,
  );
}
