/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Source,
  Source$inboundSchema,
  Source$Outbound,
  Source$outboundSchema,
} from "./source.js";

export type AnalyzeAIVisionModerationRequest = {
  source: Source;
  /**
   * Whether to perform the analysis asynchronously.
   *
   * @remarks
   * If true, the response is returned immediately and analysis is done in the background.
   * Once complete, a webhook notification will be sent to the specified URL and/or to the URLs defined in the Webhook Notifications settings of your Cloudinary Console.
   */
  async?: boolean | undefined;
  /**
   * The webhook URL to notify when the analysis is complete. Only relevant when async is set to true.
   */
  notificationUrl?: string | undefined;
  /**
   * A list of yes/no questions
   */
  rejectionQuestions?: Array<string> | undefined;
};

/** @internal */
export const AnalyzeAIVisionModerationRequest$inboundSchema: z.ZodType<
  AnalyzeAIVisionModerationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  source: Source$inboundSchema,
  async: z.boolean().optional(),
  notification_url: z.string().optional(),
  rejection_questions: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "notification_url": "notificationUrl",
    "rejection_questions": "rejectionQuestions",
  });
});

/** @internal */
export type AnalyzeAIVisionModerationRequest$Outbound = {
  source: Source$Outbound;
  async?: boolean | undefined;
  notification_url?: string | undefined;
  rejection_questions?: Array<string> | undefined;
};

/** @internal */
export const AnalyzeAIVisionModerationRequest$outboundSchema: z.ZodType<
  AnalyzeAIVisionModerationRequest$Outbound,
  z.ZodTypeDef,
  AnalyzeAIVisionModerationRequest
> = z.object({
  source: Source$outboundSchema,
  async: z.boolean().optional(),
  notificationUrl: z.string().optional(),
  rejectionQuestions: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    notificationUrl: "notification_url",
    rejectionQuestions: "rejection_questions",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnalyzeAIVisionModerationRequest$ {
  /** @deprecated use `AnalyzeAIVisionModerationRequest$inboundSchema` instead. */
  export const inboundSchema = AnalyzeAIVisionModerationRequest$inboundSchema;
  /** @deprecated use `AnalyzeAIVisionModerationRequest$outboundSchema` instead. */
  export const outboundSchema = AnalyzeAIVisionModerationRequest$outboundSchema;
  /** @deprecated use `AnalyzeAIVisionModerationRequest$Outbound` instead. */
  export type Outbound = AnalyzeAIVisionModerationRequest$Outbound;
}

export function analyzeAIVisionModerationRequestToJSON(
  analyzeAIVisionModerationRequest: AnalyzeAIVisionModerationRequest,
): string {
  return JSON.stringify(
    AnalyzeAIVisionModerationRequest$outboundSchema.parse(
      analyzeAIVisionModerationRequest,
    ),
  );
}

export function analyzeAIVisionModerationRequestFromJSON(
  jsonString: string,
): SafeParseResult<AnalyzeAIVisionModerationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyzeAIVisionModerationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyzeAIVisionModerationRequest' from JSON`,
  );
}
