/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ErrorCategory = {
  UserError: "user_error",
  AuthError: "auth_error",
  ServerError: "server_error",
  RateLimitError: "rate_limit_error",
} as const;
export type ErrorCategory = ClosedEnum<typeof ErrorCategory>;

/** @internal */
export const ErrorCategory$inboundSchema: z.ZodNativeEnum<
  typeof ErrorCategory
> = z.nativeEnum(ErrorCategory);

/** @internal */
export const ErrorCategory$outboundSchema: z.ZodNativeEnum<
  typeof ErrorCategory
> = ErrorCategory$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorCategory$ {
  /** @deprecated use `ErrorCategory$inboundSchema` instead. */
  export const inboundSchema = ErrorCategory$inboundSchema;
  /** @deprecated use `ErrorCategory$outboundSchema` instead. */
  export const outboundSchema = ErrorCategory$outboundSchema;
}
