/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const Feature = {
  GoogleTagging: "google_tagging",
  ObjectDetection: "object_detection",
  AiVision: "ai_vision",
} as const;
export type Feature = ClosedEnum<typeof Feature>;

/** @internal */
export const Feature$inboundSchema: z.ZodNativeEnum<typeof Feature> = z
  .nativeEnum(Feature);

/** @internal */
export const Feature$outboundSchema: z.ZodNativeEnum<typeof Feature> =
  Feature$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Feature$ {
  /** @deprecated use `Feature$inboundSchema` instead. */
  export const inboundSchema = Feature$inboundSchema;
  /** @deprecated use `Feature$outboundSchema` instead. */
  export const outboundSchema = Feature$outboundSchema;
}
