/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Label = {
  label: string;
  score: number;
};

export type LabelAnnotations = {
  labels?: Array<Label> | undefined;
};

export type GoogleTaggingAnalysisData = {
  labelAnnotations: LabelAnnotations;
};

/** @internal */
export const Label$inboundSchema: z.ZodType<Label, z.ZodTypeDef, unknown> = z
  .object({
    label: z.string(),
    score: z.number(),
  });

/** @internal */
export type Label$Outbound = {
  label: string;
  score: number;
};

/** @internal */
export const Label$outboundSchema: z.ZodType<
  Label$Outbound,
  z.ZodTypeDef,
  Label
> = z.object({
  label: z.string(),
  score: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Label$ {
  /** @deprecated use `Label$inboundSchema` instead. */
  export const inboundSchema = Label$inboundSchema;
  /** @deprecated use `Label$outboundSchema` instead. */
  export const outboundSchema = Label$outboundSchema;
  /** @deprecated use `Label$Outbound` instead. */
  export type Outbound = Label$Outbound;
}

export function labelToJSON(label: Label): string {
  return JSON.stringify(Label$outboundSchema.parse(label));
}

export function labelFromJSON(
  jsonString: string,
): SafeParseResult<Label, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Label$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Label' from JSON`,
  );
}

/** @internal */
export const LabelAnnotations$inboundSchema: z.ZodType<
  LabelAnnotations,
  z.ZodTypeDef,
  unknown
> = z.object({
  labels: z.array(z.lazy(() => Label$inboundSchema)).optional(),
});

/** @internal */
export type LabelAnnotations$Outbound = {
  labels?: Array<Label$Outbound> | undefined;
};

/** @internal */
export const LabelAnnotations$outboundSchema: z.ZodType<
  LabelAnnotations$Outbound,
  z.ZodTypeDef,
  LabelAnnotations
> = z.object({
  labels: z.array(z.lazy(() => Label$outboundSchema)).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LabelAnnotations$ {
  /** @deprecated use `LabelAnnotations$inboundSchema` instead. */
  export const inboundSchema = LabelAnnotations$inboundSchema;
  /** @deprecated use `LabelAnnotations$outboundSchema` instead. */
  export const outboundSchema = LabelAnnotations$outboundSchema;
  /** @deprecated use `LabelAnnotations$Outbound` instead. */
  export type Outbound = LabelAnnotations$Outbound;
}

export function labelAnnotationsToJSON(
  labelAnnotations: LabelAnnotations,
): string {
  return JSON.stringify(
    LabelAnnotations$outboundSchema.parse(labelAnnotations),
  );
}

export function labelAnnotationsFromJSON(
  jsonString: string,
): SafeParseResult<LabelAnnotations, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LabelAnnotations$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LabelAnnotations' from JSON`,
  );
}

/** @internal */
export const GoogleTaggingAnalysisData$inboundSchema: z.ZodType<
  GoogleTaggingAnalysisData,
  z.ZodTypeDef,
  unknown
> = z.object({
  label_annotations: z.lazy(() => LabelAnnotations$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "label_annotations": "labelAnnotations",
  });
});

/** @internal */
export type GoogleTaggingAnalysisData$Outbound = {
  label_annotations: LabelAnnotations$Outbound;
};

/** @internal */
export const GoogleTaggingAnalysisData$outboundSchema: z.ZodType<
  GoogleTaggingAnalysisData$Outbound,
  z.ZodTypeDef,
  GoogleTaggingAnalysisData
> = z.object({
  labelAnnotations: z.lazy(() => LabelAnnotations$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    labelAnnotations: "label_annotations",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GoogleTaggingAnalysisData$ {
  /** @deprecated use `GoogleTaggingAnalysisData$inboundSchema` instead. */
  export const inboundSchema = GoogleTaggingAnalysisData$inboundSchema;
  /** @deprecated use `GoogleTaggingAnalysisData$outboundSchema` instead. */
  export const outboundSchema = GoogleTaggingAnalysisData$outboundSchema;
  /** @deprecated use `GoogleTaggingAnalysisData$Outbound` instead. */
  export type Outbound = GoogleTaggingAnalysisData$Outbound;
}

export function googleTaggingAnalysisDataToJSON(
  googleTaggingAnalysisData: GoogleTaggingAnalysisData,
): string {
  return JSON.stringify(
    GoogleTaggingAnalysisData$outboundSchema.parse(googleTaggingAnalysisData),
  );
}

export function googleTaggingAnalysisDataFromJSON(
  jsonString: string,
): SafeParseResult<GoogleTaggingAnalysisData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GoogleTaggingAnalysisData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GoogleTaggingAnalysisData' from JSON`,
  );
}
