/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Detection = {
  name: string;
  confidence: number;
};

export type WatermarkDetectionAnalysisData = {
  detections?: Array<Detection> | undefined;
  modelVersion?: number | undefined;
};

/** @internal */
export const Detection$inboundSchema: z.ZodType<
  Detection,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  confidence: z.number(),
});

/** @internal */
export type Detection$Outbound = {
  name: string;
  confidence: number;
};

/** @internal */
export const Detection$outboundSchema: z.ZodType<
  Detection$Outbound,
  z.ZodTypeDef,
  Detection
> = z.object({
  name: z.string(),
  confidence: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Detection$ {
  /** @deprecated use `Detection$inboundSchema` instead. */
  export const inboundSchema = Detection$inboundSchema;
  /** @deprecated use `Detection$outboundSchema` instead. */
  export const outboundSchema = Detection$outboundSchema;
  /** @deprecated use `Detection$Outbound` instead. */
  export type Outbound = Detection$Outbound;
}

export function detectionToJSON(detection: Detection): string {
  return JSON.stringify(Detection$outboundSchema.parse(detection));
}

export function detectionFromJSON(
  jsonString: string,
): SafeParseResult<Detection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Detection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Detection' from JSON`,
  );
}

/** @internal */
export const WatermarkDetectionAnalysisData$inboundSchema: z.ZodType<
  WatermarkDetectionAnalysisData,
  z.ZodTypeDef,
  unknown
> = z.object({
  detections: z.array(z.lazy(() => Detection$inboundSchema)).optional(),
  model_version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "model_version": "modelVersion",
  });
});

/** @internal */
export type WatermarkDetectionAnalysisData$Outbound = {
  detections?: Array<Detection$Outbound> | undefined;
  model_version?: number | undefined;
};

/** @internal */
export const WatermarkDetectionAnalysisData$outboundSchema: z.ZodType<
  WatermarkDetectionAnalysisData$Outbound,
  z.ZodTypeDef,
  WatermarkDetectionAnalysisData
> = z.object({
  detections: z.array(z.lazy(() => Detection$outboundSchema)).optional(),
  modelVersion: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    modelVersion: "model_version",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WatermarkDetectionAnalysisData$ {
  /** @deprecated use `WatermarkDetectionAnalysisData$inboundSchema` instead. */
  export const inboundSchema = WatermarkDetectionAnalysisData$inboundSchema;
  /** @deprecated use `WatermarkDetectionAnalysisData$outboundSchema` instead. */
  export const outboundSchema = WatermarkDetectionAnalysisData$outboundSchema;
  /** @deprecated use `WatermarkDetectionAnalysisData$Outbound` instead. */
  export type Outbound = WatermarkDetectionAnalysisData$Outbound;
}

export function watermarkDetectionAnalysisDataToJSON(
  watermarkDetectionAnalysisData: WatermarkDetectionAnalysisData,
): string {
  return JSON.stringify(
    WatermarkDetectionAnalysisData$outboundSchema.parse(
      watermarkDetectionAnalysisData,
    ),
  );
}

export function watermarkDetectionAnalysisDataFromJSON(
  jsonString: string,
): SafeParseResult<WatermarkDetectionAnalysisData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WatermarkDetectionAnalysisData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WatermarkDetectionAnalysisData' from JSON`,
  );
}
